#!/usr/bin/env bash
#
# Start a network-attached instance of Ollama that mounts the same data volume.
# This is to allow for model acquisition without connecting the reset of the
# container ecosystem to the network.
#
set -e -o pipefail

SCRIPT_ABS_PATH="$(realpath "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd "$(dirname "${SCRIPT_ABS_PATH}")" && pwd)"

SCRIPT_PARAMS=()
if [[ "$#" -gt 0 ]]
then
  #echo "Using provided parameters: $*"
  SCRIPT_PARAMS=( "$@" )
fi

#echo "Final params? " "${SCRIPT_PARAMS[@]}"
"${SCRIPT_DIR}"/cli.bash "${SCRIPT_PARAMS[@]}"
